//! Speculative-decoding performance metrics.
//!
//! These are produced by an [`LlmPipeline`](crate::LlmPipeline) that was constructed via
//! [`LlmPipeline::with_draft`](crate::LlmPipeline::with_draft) and are extracted from a
//! [`DecodedResults`](crate::DecodedResults) via
//! [`DecodedResults::sd_perf_metrics`](crate::DecodedResults::sd_perf_metrics).

use crate::{drop_using_function, try_unsafe, util::Result};
use openvino_genai_sys as sys;
use std::os::raw::c_int;

/// Speculative-decoding performance metrics for both the main and draft model, plus the
/// number of tokens accepted from the draft.
pub struct SdPerfMetrics {
    ptr: *mut sys::ov_genai_sd_perf_metrics,
}
drop_using_function!(SdPerfMetrics, sys::ov_genai_sd_perf_metrics_free);

impl SdPerfMetrics {
    /// Number of draft-proposed tokens accepted by the main model across the call. Total
    /// generated tokens equals this plus one main-model token per validation step.
    pub fn num_accepted_tokens(&self) -> Result<usize> {
        let mut out: usize = 0;
        try_unsafe!(sys::ov_genai_sd_perf_metrics_get_num_accepted_tokens(
            self.ptr, &mut out
        ))?;
        Ok(out)
    }

    /// Metrics for the main model.
    pub fn main_model_metrics(&self) -> SdModelMetrics<'_> {
        SdModelMetrics {
            parent: self,
            side: 0,
        }
    }

    /// Metrics for the draft model.
    pub fn draft_model_metrics(&self) -> SdModelMetrics<'_> {
        SdModelMetrics {
            parent: self,
            side: 1,
        }
    }

    /// Construct from a raw pointer. For internal use.
    pub(crate) fn from_ptr(ptr: *mut sys::ov_genai_sd_perf_metrics) -> Self {
        Self { ptr }
    }
}

/// Borrowed view onto one side (main or draft) of an [`SdPerfMetrics`].
pub struct SdModelMetrics<'a> {
    parent: &'a SdPerfMetrics,
    side: c_int,
}

impl SdModelMetrics<'_> {
    /// Mean and standard deviation of Time-to-First-Token (ms).
    pub fn ttft(&self) -> Result<(f32, f32)> {
        self.mean_std(sys::ov_genai_sd_perf_metrics_get_ttft)
    }

    /// Mean and standard deviation of Time-to-Second-Token (ms).
    pub fn ttst(&self) -> Result<(f32, f32)> {
        self.mean_std(sys::ov_genai_sd_perf_metrics_get_ttst)
    }

    /// Mean and standard deviation of Time-per-Output-Token (ms/token).
    pub fn tpot(&self) -> Result<(f32, f32)> {
        self.mean_std(sys::ov_genai_sd_perf_metrics_get_tpot)
    }

    /// Mean and standard deviation of inference latency from the third token onward (ms).
    pub fn latency(&self) -> Result<(f32, f32)> {
        self.mean_std(sys::ov_genai_sd_perf_metrics_get_latency)
    }

    /// Mean and standard deviation of total generate-call duration (ms).
    pub fn generate_duration(&self) -> Result<(f32, f32)> {
        self.mean_std(sys::ov_genai_sd_perf_metrics_get_generate_duration)
    }

    /// Total number of tokens generated by this side.
    pub fn num_generated_tokens(&self) -> Result<usize> {
        let mut out: usize = 0;
        try_unsafe!(sys::ov_genai_sd_perf_metrics_get_num_generated_tokens(
            self.parent.ptr,
            self.side,
            &mut out
        ))?;
        Ok(out)
    }

    fn mean_std(
        &self,
        f: unsafe extern "C" fn(
            *const sys::ov_genai_sd_perf_metrics,
            c_int,
            *mut f32,
            *mut f32,
        ) -> sys::ov_status_e,
    ) -> Result<(f32, f32)> {
        let mut mean: f32 = 0.0;
        let mut std: f32 = 0.0;
        try_unsafe!(f(self.parent.ptr, self.side, &mut mean, &mut std))?;
        Ok((mean, std))
    }
}
